-- Full Courtside schema for provisioning a FRESH database.
-- Generated by `npm run schema:baseline` (last migration folded in: 017_drop_last_minute_demo.sql).
-- Executed by the migration runner ONLY when the database is empty; the
-- numbered migrations are then recorded as applied without running.
-- Do not edit by hand — regenerate after each new migration.

SET FOREIGN_KEY_CHECKS = 0;

CREATE TABLE `amis` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `user_id_1` int NOT NULL,
  `user_id_2` int NOT NULL,
  `status` varchar(20) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_amis` (`user_id_1`,`user_id_2`),
  UNIQUE KEY `uq_amis_pair` ((least(`user_id_1`,`user_id_2`)),(greatest(`user_id_1`,`user_id_2`))),
  KEY `fk_amis_user2` (`user_id_2`),
  CONSTRAINT `fk_amis_user1` FOREIGN KEY (`user_id_1`) REFERENCES `users` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_amis_user2` FOREIGN KEY (`user_id_2`) REFERENCES `users` (`id`) ON DELETE CASCADE,
  CONSTRAINT `amis_chk_1` CHECK ((`status` in (_utf8mb4'pending',_utf8mb4'accepted',_utf8mb4'rejected')))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `annonce_invitations` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `annonce_id` bigint unsigned DEFAULT NULL,
  `user_id` int DEFAULT NULL,
  `invited_by` int DEFAULT NULL,
  `status` varchar(10) DEFAULT 'pending',
  `invited_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `responded_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `annonce_id` (`annonce_id`,`user_id`),
  KEY `fk_annonce_invitations_user` (`user_id`),
  KEY `fk_annonce_invitations_inviter` (`invited_by`),
  CONSTRAINT `fk_annonce_invitations_annonce` FOREIGN KEY (`annonce_id`) REFERENCES `announcements` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_annonce_invitations_inviter` FOREIGN KEY (`invited_by`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_annonce_invitations_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `annonce_participants` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `annonce_id` bigint unsigned DEFAULT NULL,
  `user_id` int DEFAULT NULL,
  `role` varchar(20) DEFAULT NULL,
  `joined_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `fk_annonce_participants_annonce` (`annonce_id`),
  KEY `fk_annonce_participants_user` (`user_id`),
  CONSTRAINT `fk_annonce_participants_annonce` FOREIGN KEY (`annonce_id`) REFERENCES `announcements` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_annonce_participants_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE,
  CONSTRAINT `annonce_participants_chk_1` CHECK ((`role` in (_utf8mb4'creator',_utf8mb4'participant')))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `annonce_waitlist` (
  `id` int NOT NULL AUTO_INCREMENT,
  `annonce_id` bigint unsigned NOT NULL,
  `user_id` int NOT NULL,
  `notified_at` datetime DEFAULT NULL,
  `created_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_waitlist_entry` (`annonce_id`,`user_id`),
  KEY `idx_waitlist_annonce` (`annonce_id`,`created_at`),
  KEY `fk_annonce_waitlist_user` (`user_id`),
  CONSTRAINT `fk_annonce_waitlist_annonce` FOREIGN KEY (`annonce_id`) REFERENCES `announcements` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_annonce_waitlist_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `announcements` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `sport_type` varchar(50) NOT NULL,
  `slot_id` bigint unsigned DEFAULT NULL,
  `terrain_id` bigint unsigned DEFAULT NULL,
  `slot_start` timestamp NOT NULL,
  `slot_end` timestamp NOT NULL,
  `places_total` int NOT NULL,
  `places_disponibles` int NOT NULL,
  `description` text,
  `manual_address` varchar(500) DEFAULT NULL,
  `manual_city` varchar(100) DEFAULT NULL,
  `created_by` int DEFAULT NULL,
  `status` enum('active','expired','cancelled','validated') DEFAULT 'active',
  `reservation_id` bigint unsigned DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `visibility` varchar(10) DEFAULT 'public',
  `public_place_id` varchar(50) DEFAULT NULL COMMENT 'Identifiant équipement data.gouv.fr (equip_numero) pour les lieux publics',
  `expiration_date` timestamp NULL DEFAULT NULL COMMENT 'Date limite d''inscription (par défaut 24h avant slot_start)',
  `auto_cancel` tinyint(1) DEFAULT '1' COMMENT 'Annuler automatiquement si pas assez de participants avant expiration',
  `min_participants` int DEFAULT '2' COMMENT 'Nombre minimum de participants requis pour ne pas annuler',
  `lat` decimal(10,8) DEFAULT NULL,
  `lng` decimal(11,8) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `fk_announcements_reservation_id` (`reservation_id`),
  KEY `idx_announcements_slot_id` (`slot_id`),
  KEY `idx_announcements_status` (`status`),
  KEY `idx_announcements_public_place_id` (`public_place_id`),
  KEY `idx_expiration_status` (`expiration_date`,`status`),
  KEY `idx_slot_start_status` (`slot_start`,`status`),
  KEY `fk_announcements_terrain` (`terrain_id`),
  KEY `fk_announcements_creator` (`created_by`),
  CONSTRAINT `fk_announcements_creator` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_announcements_reservation_id` FOREIGN KEY (`reservation_id`) REFERENCES `reservations` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_announcements_slot_id` FOREIGN KEY (`slot_id`) REFERENCES `slots` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_announcements_terrain` FOREIGN KEY (`terrain_id`) REFERENCES `terrains` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `availability_exceptions` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `terrain_id` bigint unsigned NOT NULL,
  `date` date NOT NULL,
  `is_closed` tinyint(1) DEFAULT '0',
  `special_open_time` time DEFAULT NULL,
  `special_close_time` time DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `terrain_id` (`terrain_id`),
  CONSTRAINT `availability_exceptions_ibfk_1` FOREIGN KEY (`terrain_id`) REFERENCES `terrains` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `chat_participants` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `chat_id` bigint unsigned NOT NULL,
  `user_id` int NOT NULL,
  `role` enum('member','admin') DEFAULT 'member',
  `joined_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `last_read_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `chat_id` (`chat_id`),
  KEY `user_id` (`user_id`),
  CONSTRAINT `chat_participants_ibfk_1` FOREIGN KEY (`chat_id`) REFERENCES `chats` (`id`) ON DELETE CASCADE,
  CONSTRAINT `chat_participants_ibfk_2` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `chats` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(255) DEFAULT NULL,
  `type` enum('private','group','annonce') NOT NULL DEFAULT 'private',
  `status` enum('accepted','pending','rejected') NOT NULL DEFAULT 'accepted',
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `closed_at` timestamp NULL DEFAULT NULL,
  `announcement_id` bigint unsigned DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_chats_announcement` (`announcement_id`),
  CONSTRAINT `fk_chats_announcement` FOREIGN KEY (`announcement_id`) REFERENCES `announcements` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `club_images` (
  `id` int NOT NULL AUTO_INCREMENT,
  `club_id` int NOT NULL,
  `image_url` varchar(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_club_image` (`club_id`,`image_url`),
  CONSTRAINT `club_images_ibfk_1` FOREIGN KEY (`club_id`) REFERENCES `clubs` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `club_opening_hours` (
  `id` int NOT NULL AUTO_INCREMENT,
  `club_id` int NOT NULL,
  `day_of_week` int NOT NULL,
  `open_time` time DEFAULT NULL,
  `close_time` time DEFAULT NULL,
  `is_closed` tinyint(1) DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `club_id` (`club_id`),
  CONSTRAINT `club_opening_hours_ibfk_1` FOREIGN KEY (`club_id`) REFERENCES `clubs` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `club_payment_methods` (
  `id` int NOT NULL AUTO_INCREMENT,
  `club_id` int NOT NULL,
  `method` varchar(50) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `club_id` (`club_id`),
  CONSTRAINT `club_payment_methods_ibfk_1` FOREIGN KEY (`club_id`) REFERENCES `clubs` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `club_socials` (
  `id` int NOT NULL AUTO_INCREMENT,
  `club_id` int NOT NULL,
  `type` varchar(30) NOT NULL,
  `url` varchar(200) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `club_id` (`club_id`),
  CONSTRAINT `club_socials_ibfk_1` FOREIGN KEY (`club_id`) REFERENCES `clubs` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `club_sports` (
  `id` int NOT NULL AUTO_INCREMENT,
  `club_id` int NOT NULL,
  `sport_name` varchar(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_club_sport` (`club_id`,`sport_name`),
  CONSTRAINT `club_sports_ibfk_1` FOREIGN KEY (`club_id`) REFERENCES `clubs` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `clubs` (
  `id` int NOT NULL AUTO_INCREMENT,
  `name` varchar(100) NOT NULL,
  `address` varchar(255) DEFAULT NULL,
  `city` varchar(100) DEFAULT NULL,
  `lat` decimal(9,6) DEFAULT NULL,
  `lon` decimal(9,6) DEFAULT NULL,
  `stripe_account_id` varchar(255) DEFAULT NULL,
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  `rating` decimal(2,1) DEFAULT NULL,
  `postal_code` varchar(20) DEFAULT NULL,
  `phone` varchar(30) DEFAULT NULL,
  `email` varchar(100) DEFAULT NULL,
  `website` varchar(200) DEFAULT NULL,
  `description` text,
  `cancellation_policy` text,
  `status` varchar(10) NOT NULL DEFAULT 'attente',
  PRIMARY KEY (`id`),
  CONSTRAINT `clubs_chk_1` CHECK ((`status` in (_utf8mb4'attente',_utf8mb4'confirme')))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `clubs_stats` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `club_id` int DEFAULT NULL,
  `total_reservations` int DEFAULT '0',
  `total_revenue` decimal(10,2) DEFAULT '0.00',
  `popular_terrain_id` bigint unsigned DEFAULT NULL,
  `last_updated` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_clubs_stats_club` (`club_id`),
  KEY `fk_clubs_stats_terrain` (`popular_terrain_id`),
  CONSTRAINT `fk_clubs_stats_club` FOREIGN KEY (`club_id`) REFERENCES `clubs` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_clubs_stats_terrain` FOREIGN KEY (`popular_terrain_id`) REFERENCES `terrains` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `event_images` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `event_id` bigint unsigned NOT NULL,
  `image_url` text NOT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `fk_event_images_event` (`event_id`),
  CONSTRAINT `fk_event_images_event` FOREIGN KEY (`event_id`) REFERENCES `events` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `events` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `club_id` int DEFAULT NULL,
  `terrain_id` bigint unsigned DEFAULT NULL,
  `title` varchar(150) NOT NULL,
  `description` text,
  `event_type` varchar(50) DEFAULT NULL,
  `start_time` timestamp NOT NULL,
  `end_time` timestamp NOT NULL,
  `external_link` text,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `fk_events_club` (`club_id`),
  KEY `fk_events_terrain` (`terrain_id`),
  CONSTRAINT `fk_events_club` FOREIGN KEY (`club_id`) REFERENCES `clubs` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_events_terrain` FOREIGN KEY (`terrain_id`) REFERENCES `terrains` (`id`) ON DELETE SET NULL,
  CONSTRAINT `events_chk_1` CHECK ((`event_type` in (_utf8mb4'tournament',_utf8mb4'match',_utf8mb4'training')))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `favorites` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `user_id` int DEFAULT NULL,
  `terrain_id` bigint unsigned DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_favorites` (`user_id`,`terrain_id`),
  KEY `fk_favorites_terrain` (`terrain_id`),
  CONSTRAINT `fk_favorites_terrain` FOREIGN KEY (`terrain_id`) REFERENCES `terrains` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_favorites_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `messages` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `chat_id` bigint unsigned NOT NULL,
  `sender_id` int DEFAULT NULL,
  `content` text,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `file_url` varchar(255) DEFAULT NULL,
  `file_type` varchar(50) DEFAULT NULL,
  `message_type` enum('text','invitation','system','booking_request') DEFAULT 'text',
  `invitation_id` bigint unsigned DEFAULT NULL,
  `metadata` json DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `fk_invitation` (`invitation_id`),
  KEY `idx_messages_chat_created` (`chat_id`,`created_at`),
  KEY `fk_messages_sender` (`sender_id`),
  CONSTRAINT `fk_invitation` FOREIGN KEY (`invitation_id`) REFERENCES `annonce_invitations` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_messages_chat` FOREIGN KEY (`chat_id`) REFERENCES `chats` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_messages_sender` FOREIGN KEY (`sender_id`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `newsletter_subscribers` (
  `id` int NOT NULL AUTO_INCREMENT,
  `email` varchar(254) NOT NULL,
  `created_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_newsletter_email` (`email`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `notifications` (
  `id` int NOT NULL AUTO_INCREMENT,
  `user_id` int NOT NULL,
  `type` varchar(40) NOT NULL,
  `payload` json DEFAULT NULL,
  `read_at` datetime DEFAULT NULL,
  `created_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_notifications_user` (`user_id`,`read_at`),
  KEY `idx_notifications_created` (`created_at`),
  CONSTRAINT `fk_notifications_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `password_resets` (
  `id` int NOT NULL AUTO_INCREMENT,
  `user_id` int NOT NULL,
  `token_hash` char(64) NOT NULL,
  `expires_at` datetime NOT NULL,
  `used_at` datetime DEFAULT NULL,
  `created_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_password_resets_token` (`token_hash`),
  KEY `idx_password_resets_user` (`user_id`),
  CONSTRAINT `fk_password_resets_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `payments` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `reservation_id` bigint unsigned DEFAULT NULL,
  `amount` decimal(8,2) NOT NULL,
  `payment_method` varchar(50) NOT NULL,
  `status` varchar(20) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `fk_payments_reservation` (`reservation_id`),
  CONSTRAINT `fk_payments_reservation` FOREIGN KEY (`reservation_id`) REFERENCES `reservations` (`id`) ON DELETE SET NULL,
  CONSTRAINT `payments_chk_1` CHECK ((`status` in (_utf8mb4'pending',_utf8mb4'succeeded',_utf8mb4'failed')))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `player_ratings` (
  `id` int NOT NULL AUTO_INCREMENT,
  `annonce_id` bigint unsigned NOT NULL,
  `rater_id` int NOT NULL,
  `rated_user_id` int NOT NULL,
  `rating` tinyint NOT NULL,
  `created_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_player_rating` (`annonce_id`,`rater_id`,`rated_user_id`),
  KEY `idx_player_ratings_rated` (`rated_user_id`),
  KEY `fk_player_ratings_rater` (`rater_id`),
  CONSTRAINT `fk_player_ratings_annonce` FOREIGN KEY (`annonce_id`) REFERENCES `announcements` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_player_ratings_rated` FOREIGN KEY (`rated_user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_player_ratings_rater` FOREIGN KEY (`rater_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `recurring_availabilities` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `terrain_id` bigint unsigned NOT NULL,
  `day_of_week` tinyint NOT NULL,
  `start_time` time NOT NULL,
  `end_time` time NOT NULL,
  `is_closed` tinyint(1) DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `terrain_id` (`terrain_id`),
  CONSTRAINT `recurring_availabilities_ibfk_1` FOREIGN KEY (`terrain_id`) REFERENCES `terrains` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `reservation_participants` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `reservation_id` bigint unsigned NOT NULL,
  `user_id` int DEFAULT NULL,
  `name` varchar(255) DEFAULT NULL,
  `email` varchar(255) DEFAULT NULL,
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_reservation_participants_reservation` (`reservation_id`),
  KEY `fk_reservation_participants_user` (`user_id`),
  CONSTRAINT `fk_reservation_participants_reservation` FOREIGN KEY (`reservation_id`) REFERENCES `reservations` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_reservation_participants_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `reservation_share_payments` (
  `id` int NOT NULL AUTO_INCREMENT,
  `reservation_id` bigint unsigned NOT NULL,
  `stripe_session_id` varchar(120) NOT NULL,
  `amount` decimal(8,2) NOT NULL,
  `payer_email` varchar(254) DEFAULT NULL,
  `created_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_share_session` (`stripe_session_id`),
  KEY `idx_share_reservation` (`reservation_id`),
  CONSTRAINT `fk_share_payments_reservation` FOREIGN KEY (`reservation_id`) REFERENCES `reservations` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `reservations` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `user_id` int DEFAULT NULL,
  `terrain_id` bigint unsigned DEFAULT NULL,
  `start_time` timestamp NOT NULL,
  `end_time` timestamp NOT NULL,
  `price` decimal(8,2) NOT NULL,
  `status` varchar(20) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `stripe_session_id` varchar(120) DEFAULT NULL,
  `split_total` tinyint DEFAULT NULL,
  `reminder_sent_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_reservations_stripe_session` (`stripe_session_id`),
  KEY `fk_reservations_user` (`user_id`),
  KEY `fk_reservations_terrain` (`terrain_id`),
  CONSTRAINT `fk_reservations_terrain` FOREIGN KEY (`terrain_id`) REFERENCES `terrains` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_reservations_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `reservations_chk_1` CHECK ((`status` in (_utf8mb4'pending',_utf8mb4'confirmed',_utf8mb4'cancelled',_utf8mb4'paid')))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `reviews` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `user_id` int DEFAULT NULL,
  `club_id` int DEFAULT NULL,
  `public_place_id` varchar(50) DEFAULT NULL,
  `rating` int DEFAULT NULL,
  `comment` text,
  `response` text,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_reviews_public_place_id` (`public_place_id`),
  KEY `fk_reviews_user` (`user_id`),
  KEY `fk_reviews_club` (`club_id`),
  CONSTRAINT `fk_reviews_club` FOREIGN KEY (`club_id`) REFERENCES `clubs` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_reviews_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `reviews_chk_1` CHECK ((`rating` between 1 and 5))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `slots` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `club_id` int DEFAULT NULL,
  `terrain_id` bigint unsigned NOT NULL,
  `date` date NOT NULL,
  `start_time` time NOT NULL,
  `end_time` time NOT NULL,
  `status` varchar(20) NOT NULL DEFAULT 'free',
  `reservation_id` bigint unsigned DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_slots_unique_slot` (`terrain_id`,`date`,`start_time`),
  KEY `reservation_id` (`reservation_id`),
  KEY `idx_slots_club_date_status_start` (`club_id`,`date`,`status`,`start_time`),
  KEY `idx_slots_status` (`status`),
  CONSTRAINT `fk_slots_club` FOREIGN KEY (`club_id`) REFERENCES `clubs` (`id`),
  CONSTRAINT `slots_ibfk_1` FOREIGN KEY (`terrain_id`) REFERENCES `terrains` (`id`),
  CONSTRAINT `slots_ibfk_2` FOREIGN KEY (`reservation_id`) REFERENCES `reservations` (`id`),
  CONSTRAINT `slots_chk_status` CHECK ((`status` in (_utf8mb4'free',_utf8mb4'booked',_utf8mb4'blocked')))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `terrain_images` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `terrain_id` bigint unsigned NOT NULL,
  `image_url` varchar(512) NOT NULL,
  `display_order` int DEFAULT '0',
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_terrain_id` (`terrain_id`),
  CONSTRAINT `terrain_images_ibfk_1` FOREIGN KEY (`terrain_id`) REFERENCES `terrains` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `terrains` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `club_id` int DEFAULT NULL,
  `name` varchar(100) NOT NULL,
  `sport_type` varchar(50) NOT NULL,
  `price_per_hour` decimal(8,2) NOT NULL,
  `slot_duration` int NOT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `fk_terrains_club` (`club_id`),
  CONSTRAINT `fk_terrains_club` FOREIGN KEY (`club_id`) REFERENCES `clubs` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `user_profiles` (
  `user_id` int NOT NULL,
  `birthdate` date DEFAULT NULL,
  `city` varchar(100) DEFAULT NULL,
  `bio` text,
  `sports` json DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `is_public` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`user_id`),
  CONSTRAINT `fk_user_profiles_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `users` (
  `id` int NOT NULL AUTO_INCREMENT,
  `name` varchar(100) NOT NULL,
  `email` varchar(255) NOT NULL,
  `password_hash` varchar(255) NOT NULL,
  `role` varchar(20) DEFAULT NULL,
  `club_id` int DEFAULT NULL,
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  `avatar` varchar(255) DEFAULT NULL,
  `username` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `email` (`email`),
  UNIQUE KEY `username` (`username`),
  KEY `fk_users_club` (`club_id`),
  CONSTRAINT `fk_users_club` FOREIGN KEY (`club_id`) REFERENCES `clubs` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `users_chk_role` CHECK ((`role` in (_utf8mb4'player',_utf8mb4'club_admin')))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

SET FOREIGN_KEY_CHECKS = 1;
