/**
 * Regenerates src/migrations/baseline.sql from the live database.
 *
 * baseline.sql is the full schema (structure only, no data) used by the
 * migration runner to provision a FRESH database in one shot; the runner
 * then records every numbered migration as applied. Existing databases
 * never execute it. Regenerate after adding a migration:
 *   npm run schema:baseline
 */
require('dotenv').config();
const fs = require('fs');
const path = require('path');
const mysql = require('mysql2');

const c = mysql.createConnection({
  host: process.env.DB_HOST, user: process.env.DB_USER,
  password: process.env.DB_PASSWORD, database: process.env.DB_NAME, port: process.env.DB_PORT,
});
const q = (sql) => new Promise((res, rej) => c.query(sql, (e, r) => (e ? rej(e) : res(r))));

const OUT = path.join(__dirname, '..', 'src', 'migrations', 'baseline.sql');

(async () => {
  const tables = (await q('SHOW TABLES')).map(r => Object.values(r)[0])
    .filter(t => t !== 'schema_migrations'); // the runner owns that one
  const last = (await q('SELECT MAX(filename) f FROM schema_migrations'))[0].f || 'aucune';

  let sql = `-- Full Courtside schema for provisioning a FRESH database.
-- Generated by \`npm run schema:baseline\` (last migration folded in: ${last}).
-- Executed by the migration runner ONLY when the database is empty; the
-- numbered migrations are then recorded as applied without running.
-- Do not edit by hand — regenerate after each new migration.

SET FOREIGN_KEY_CHECKS = 0;

`;
  for (const t of tables) {
    const create = (await q(`SHOW CREATE TABLE \`${t}\``))[0]['Create Table']
      .replace(/ AUTO_INCREMENT=\d+/, ''); // no counters in a fresh schema
    sql += create + ';\n\n';
  }
  sql += 'SET FOREIGN_KEY_CHECKS = 1;\n';

  fs.writeFileSync(OUT, sql);
  console.log(`written ${OUT} (${tables.length} tables)`);
  process.exit(0);
})().catch(e => { console.error(e.message); process.exit(1); });
